- name: Install three tier applications on appsdb host group
  hosts: appdbs
  gather_facts: false
  become: true
  vars:
     GUID: "6e2f"

  roles:
    - { role: "./roles/common" }
    - { role: "./roles/appdbs" }

